//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_WITH_ANGULAR_JS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public int Emp_Id { get; set; }
        public string Emp_Name { get; set; }
        public string Emp_City { get; set; }
        public string Emp_Age { get; set; }
    }
}
